# Etapa 1: Construcción de la aplicación
FROM node:18-alpine AS builder

WORKDIR /app

# Instalamos pnpm globalmente
RUN npm install -g pnpm

# Copiamos los archivos de dependencias. Se asume que usas "pnpm-lock.yaml"
COPY package.json pnpm-lock.yaml ./

# Instalamos las dependencias usando pnpm
RUN pnpm install --frozen-lockfile

# Copiamos el resto de la aplicación
COPY . .

# Construimos la aplicación para producción
RUN pnpm build

# Etapa 2: Imagen final de producción
FROM node:18-alpine

WORKDIR /app

# Instalamos pnpm en la imagen final (si lo necesitas para ejecutar scripts)
RUN npm install -g pnpm

# Copiamos la aplicación construida desde la etapa anterior
COPY --from=builder /app ./

# Exponemos el puerto en el que Next.js escucha (por defecto es el 3000)
EXPOSE 3000

# Ejecutamos la aplicación en modo producción
CMD ["pnpm", "start"]
